seed: 0 # random seed for reproducibility
save_dir: ${scratch_root}/checkpoints/ # save directory for evaluation results
run_name: null # name of the run to be evaluated
return_diffusion_chain: false # if true, also return the full (x_agent, x_lane) chain at every diffusion step from sampling